### ISSUE TITLE
Are there any plans to add #nixos to the list of channels on ircbrowse.net?

### ISSUE THREAD

**Issue by DonManley** [chrisdone/ircbrowse#14]
I'm not sure if this is the right place to ask this question, but I was not able to find any contact on IRCBrowse. Nix packages manager is quite popular among haskellers and it is used by some projects, which channels were already added (e.g., #reflexfrp which uses try-reflex that depends on nix).  Some people have nix related discussions on various haskell channels, but the haskell related discussions on nix channels (nix package manager has great support for haskell) have extremely poor discoverability. IMO, it would be amazing to have the ircbrowse level usability for the nixos channel.

**Comment by chrisdone** [comment]
I just need consent from the channel operator and therefore consensus from the channel participants that it's okay to publicly log the conversation. Then it's a matter of a few minutes to add a new channel.

**Comment by DonManley** [comment]
It's okay to publicly log the conversation. They are logging it themselves to http://nixos.org/irc/logs/ and bot.me logs has a web interface to browse them. It's just that the former is not as user-friendly and the latter is not as feature-rich as ircbrowse. I did not talk to the channel founded, but people I've talked to are totally on board with having more ways to access logs.

**Comment by chrisdone** [comment]
Fair enough, existent public logs are good enough justification to add to IRCBrowse.
