### ISSUE TITLE
IRCBrowse bot seems to be down

### ISSUE THREAD

**Issue by 23Skidoo** [chrisdone/ircbrowse#29]
See here: http://ircbrowse.net/browse/hackage?events_page=1015

Looks like it hasn't been archiving for the last few days.

**Comment by chrisdone** [comment]
Checking ...

**Comment by chrisdone** [comment]
Fixed. When I had the downtime issues, I put in that message. But it messes with the importing process. I reset the logs from 2017-08-12 onwards and now they'll be re-imported and back on track during the next 24 hours.  

Thanks for flagging it up.

**Comment by 23Skidoo** [comment]
Thanks!

**Comment by 23Skidoo** [comment]
@chrisdone All `#hackage` logs pages after 1015 are empty now, e.g.: http://ircbrowse.net/browse/hackage?events_page=1015, I assume that you're aware and it will fix itself automatically somehow?

**Comment by chrisdone** [comment]
@23Skidoo Yeah, it just needed to update and get back in sync: http://ircbrowse.net/browse/hackage?events_page=1021 I ran the cronjob just for that channel and it fixed itself.

The rest should follow suit. The full next scheduled cronjob is in a couple minutes.

**Comment by 23Skidoo** [comment]
Great, thanks!
